from . import contacts_wt
from . import crm_wt
from . import invoice_wt
from . import purchase_wt
from . import sale_wt
from . import stock_wt
from . import recruitment_wt
from . import project_wt
from . import phone_calls
