from . import hr_job
from . import hr_job_skill
from . import hr_interview
from . import hr_interview_skill
from . import hr_applicant
from . import hr_interview_questions
from . import hr_interview_stage
from . import calendar
from . import res_config_settings
from . import hr_interview_wizard
