{
    'name': 'HR Letters',
    'version': "16.0",
    'category': 'Human Resources Letters',
    'summary': 'Letters for employees and applicant',
    'description': """Letters for employees and applicant""",
    'author': 'Technians Softech Pvt. Ltd.',
    'company': 'Technians Softech Pvt. Ltd.',
    'maintainer': 'Technians Softech Pvt. Ltd.',
    'website': 'https://technians.com/',
    'depends': ['base', 'hr_recruitment','hr_contract','hr_payroll_community'],
    'data': [
        'security/ir.model.access.csv',
        'security/letter_groups.xml',
        'reports/report_actions.xml',
        'views/base_document_layout_view.xml',
        'views/res_config_settings_view.xml',
        'data/mail_templates.xml',
        'reports/report_templates.xml',
        'views/hr_letters_views.xml',
        'views/ts_report_templates.xml',
        'views/server_actions.xml',
        'wizards/wiz_appointment_letters_view.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'price': 50,
    'currency': 'USD'
}